- name: Update package cache (RedHat/CentOS/Fedora)
  ansible.builtin.dnf:
    update_cache: yes

- name: Install Nginx (RedHat/CentOS/Fedora)
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Ensure Nginx service is running and enabled
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes

- name: Get Nginx version
  ansible.builtin.command: nginx -v
  register: nginx_version_output
  changed_when: false 

- name: Display Nginx version
  ansible.builtin.debug:
    msg: "Nginx version installed: {{ nginx_version_output.stderr | regex_replace('^nginx version: ', '') }}"
       