

- name: Update package cache (RedHat/CentOS/Fedora)
  ansible.builtin.dnf:
    update_cache: yes

- name: Install EPEL repo for newer Python (RedHat/CentOS/Fedora)
  ansible.builtin.dnf:
    name: epel-release
    state: present      

- name: Install Python 3.12 and pip (RedHat/CentOS/Fedora)
  ansible.builtin.dnf:
    name:
      - python3.12 
      - python3-pip
    state: present
    enablerepo: epel 
  ignore_errors: yes 

- name: Fallback to generic python3 if 3.12 not found (RedHat/CentOS/Fedora)
  ansible.builtin.dnf:
    name:
      - python3
      - python3-pip
    state: present
    enablerepo: epel
  when: ansible_facts['packages']['python3.12'] is not defined or ansible_facts['packages']['python3.12'][0]['version'] is not search('^3\\.12')

- name: Get Python 3 version
  ansible.builtin.command: python3 --version
  register: python_version_output
  changed_when: false 

- name: Display Python 3 version
  ansible.builtin.debug:
    msg: "Python 3 version installed: {{ python_version_output.stdout }}"


- name: Install Nginx (RedHat/CentOS/Fedora)
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Ensure Nginx service is running and enabled
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes

- name: Get Nginx version
  ansible.builtin.command: nginx -v
  register: nginx_version_output
  changed_when: false 

- name: Display Nginx version
  ansible.builtin.debug:
    msg: "Nginx version installed: {{ nginx_version_output.stderr | regex_replace('^nginx version: ', '') }}"

- name: Open port with firewalld (RedHat/CentOS/Fedora)
  ansible.posix.firewalld:
    zone: public           
    port: "80/tcp"
    state: enabled         
    permanent: yes         
    immediate: yes         