# - name: Update package cache (RedHat/CentOS/Fedora)
#   ansible.builtin.dnf:
#     update_cache: yes

- name: Install EPEL repo for newer Python (RedHat/CentOS/Fedora)
  ansible.builtin.dnf:
    name: epel-release
    state: present      

- name: Install Python 3.12 and pip (RedHat/CentOS/Fedora)
  ansible.builtin.dnf:
    name:
      - python3.12 
      - python3-pip
    state: present
    enablerepo: epel 
  ignore_errors: yes 

- name: Fallback to generic python3 if 3.12 not found (RedHat/CentOS/Fedora)
  ansible.builtin.dnf:
    name:
      - python3
      - python3-pip
    state: present
    enablerepo: epel
  when: ansible_facts['packages']['python3.12'] is not defined or ansible_facts['packages']['python3.12'][0]['version'] is not search('^3\\.12')

- name: Get Python 3 version
  ansible.builtin.command: python3 --version
  register: python_version_output
  changed_when: false 

- name: Display Python 3 version
  ansible.builtin.debug:
    msg: "Python 3 version installed: {{ python_version_output.stdout }}"
