
- name: Get systemctl status for {{ app_name }}
  ansible.builtin.command: systemctl status {{ app_name }}
  register: service_status_output
  changed_when: false
  ignore_errors: yes

- name: Extract and print active status
  ansible.builtin.debug:
    msg: "{{ (service_status_output.stdout_lines | select('search', 'Active:') | list)[0] | default('Active status not found') }}"

- name: Fail if service is not active (optional)
  ansible.builtin.fail:
    msg: "{{ app_name }} service is not active or failed!"
  when: service_status_output.rc != 0 or "active (running)" not in service_status_output.stdout