- name: Update all packages to the latest version
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Clean up old packages and remove unneeded dependencies
  ansible.builtin.dnf:
    autoremove: yes

- name: Clean DNF cache using command module
  ansible.builtin.command: dnf clean all

- name: Check if a reboot is required after updates
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if the system requires it
  ansible.builtin.reboot:
    reboot_timeout: 600
  when: reboot_required_file.stat.exists

- name: Verify kernel version after reboot (optional)
  ansible.builtin.debug:
    msg: "Kernel version after update: {{ ansible_kernel }}"
  when: reboot_required_file.stat.exists