---
- name: Load plugin list from file
  ansible.builtin.set_fact:
    jenkins_plugins: "{{ lookup('file', 'plugins.txt').splitlines() }}"

- name: Read initial admin password
  ansible.builtin.command: cat {{ jenkins_home }}/secrets/initialAdminPassword
  register: initial_password_command_output

- name: Install Jenkins plugins from list
  community.general.jenkins_plugin:
    name: "{{ item }}"
    state: present
    url: "http://localhost:{{jenkins_http_port}}"
    url_username: admin 
    url_password: "{{ initial_password_command_output.stdout | trim }}" 
  loop: "{{ jenkins_plugins }}"

- name: Stop Jenkins service
  ansible.builtin.service:
    name: jenkins
    state: stopped 

- name: Create Jenkins CasC directory
  ansible.builtin.file:
    path: "{{ jenkins_casc }}"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0755'

- name: Copy JCasC configuration file to remote host
  ansible.builtin.copy:
    src: "jenkins.yaml"
    dest: "{{ jenkins_casc }}/jenkins.yaml"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0644'

- name: Deploy manual jenkins.service file with JCasC 
  ansible.builtin.template:
    src: jenkins.service.jcasc.j2
    dest: /etc/systemd/system/jenkins.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon after service file change
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start Jenkins service
  ansible.builtin.service:
    name: jenkins
    state: started

