- name: Install Docker and required packages
  dnf:
    name:
      - docker
      - python3-docker
      - awscli
    state: present

- name: Enable Docker
  service:
    name: docker
    state: started
    enabled: true

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: true
