image: hashicorp/terraform:1.6.6   

variables:
  AWS_REGION: "eu-central-1"

stages:
  - validate
  - plan
  - apply

before_script:
  - apk add --no-cache curl unzip bash python3 py3-pip
  - pip install awscli
  - terraform --version

validate:
  stage: validate
  script:
    - terraform init -input=false   
    - terraform validate

plan:
  stage: plan
  script:
    - terraform init -input=false   
    - terraform plan -out=plan.tfplan
  artifacts:
    paths:
      - plan.tfplan

apply:
  stage: apply
  script:
    - terraform init -input=false   
    - terraform apply -auto-approve plan.tfplan
  dependencies:
    - plan
  only:
    - main  
  when: manual  
