- name: Stop and disable Flask app service if it exists
  ansible.builtin.systemd:
    name: "{{ backend_name }}.service"
    state: stopped
    enabled: no
    daemon_reload: yes
  ignore_errors: yes

- name: Remove Flask app systemd service file
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ backend_name }}.service"
    state: absent
  ignore_errors: yes

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Remove application directory
  ansible.builtin.file:
    path: "{{backend_app_directory }}"
    state: absent
  ignore_errors: yes

- name: Remove application user
  ansible.builtin.user:
    name: "{{ python_user }}"
    state: absent
    remove: yes
    force: yes
  ignore_errors: yes

- name: Remove application group
  ansible.builtin.group:
    name: "{{ python_group }}"
    state: absent
  ignore_errors: yes
